name: Test ASP.NET API

on:
  push:
    branches:
      - main  # Runs on push to main branch
  pull_request:
    branches:
      - main  # Runs on PR to main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'  # Change this to your .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build API
        run: dotnet build --configuration Release --no-restore

      - name: Run API Server (Background)
        run: |
          dotnet run --configuration Release --project YourApiProject.csproj &
          sleep 10  # Wait 10 seconds for the server to start

      - name: Test API with Curl
        run: |
          curl --fail http://localhost:5000/api/categories

      - name: Run Automated Tests
        run: dotnet test --configuration Release --no-restore
