name: Test ASP.NET API

on:
  push:
    branches:
      - main  # Runs tests when pushing to main branch
  pull_request:
    branches:
      - main  # Runs tests when creating a PR

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'  # Change this to match your .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build API
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test --configuration Release --no-restore --logger "trx;LogFileName=test_results.trx"

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: '**/test_results.trx'
